# .bash_profile

alias vi='/usr/bin/vim'

# User specific environment and startup programs

PATH=$HOME/bin:/opt/rh/ruby193/root/usr/bin::/bin:/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin

LD_LIBRARY_PATH=/opt/rh/ruby193/root/usr/lib64:

export PATH
export LD_LIBRARY_PATH
