FROM tdmedia/mysql
MAINTAINER Rob Taylor <rt@tdmedia.com>

RUN yum -y update; yum clean all

# We need Ruby 1.9.3 to run Capistrano
RUN yum install -y centos-release-SCL
RUN yum install -y ruby193 rubygems
RUN gem install bundler

# install node
RUN yum -y install nodejs npm; yum clean all
# still using grunt
RUN npm install -g grunt grunt-cli bower

# install samba
RUN yum install -y samba; yum clean all

# composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
