FROM tdmedia/mysql
MAINTAINER Rob Taylor <rt@tdmedia.com>

RUN yum -y update; yum clean all

# Install the latest Ruby
RUN gpg2 --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3
RUN curl -L get.rvm.io | bash -s stable
RUN source /etc/profile.d/rvm.sh
RUN /bin/bash -l -c "rvm requirements"
RUN /bin/bash -l -c "rvm install ruby"
RUN /bin/bash -l -c "gem install bundler --no-ri --no-rdoc"

# install node
RUN yum -y install nodejs npm; yum clean all
# still using grunt
RUN npm install -g grunt grunt-cli bower

# install samba
RUN yum install -y samba; yum clean all

# composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
